apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  selector:
    matchLabels:
      app: webservice
  replicas: 1
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice  
        image: <Url da Imagem>
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocirsecret     
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webservice